enum MLModelLabelText: String {
    case objectMLModelPerson
    case objectMLModelBicycle
    case objectMLModelCar
    case objectMLModelMotorbike
    case objectMLModelAeroplane
    case objectMLModelBus
    case objectMLModelTrain
    case objectMLModelTruck
    case objectMLModelBoat
    case objectMLModelTrafficLight
    case objectMLModelFireHydrant
    case objectMLModelStopSign
    case objectMLModelParkingMeter
    case objectMLModelBench
    case objectMLModelBird
    case objectMLModelCat
    case objectMLModelDog
    case objectMLModelHorse
    case objectMLModelSheep
    case objectMLModelCow
    case objectMLModelElephant
    case objectMLModelBear
    case objectMLModelZebra
    case objectMLModelGiraffe
    case objectMLModelBackpack
    case objectMLModelUmbrella
    case objectMLModelHandbag
    case objectMLModelTie
    case objectMLModelSuitcase
    case objectMLModelFrisbee
    case objectMLModelSkis
    case objectMLModelSnowboard
    case objectMLModelSportsBall
    case objectMLModelKite
    case objectMLModelBaseballBat
    case objectMLModelBaseballGlove
    case objectMLModelSkateboard
    case objectMLModelSurfboard
    case objectMLModelTennisRacket
    case objectMLModelBottle
    case objectMLModelWineGlass
    case objectMLModelCup
    case objectMLModelFork
    case objectMLModelKnife
    case objectMLModelSpoon
    case objectMLModelBowl
    case objectMLModelBanana
    case objectMLModelApple
    case objectMLModelSandwich
    case objectMLModelOrange
    case objectMLModelBroccoli
    case objectMLModelCarrot
    case objectMLModelHotDog
    case objectMLModelPizza
    case objectMLModelDonut
    case objectMLModelCake
    case objectMLModelChair
    case objectMLModelSofa
    case objectMLModelPottedPlant
    case objectMLModelBed
    case objectMLModelDiningTable
    case objectMLModelToilet
    case objectMLModelTVMonitor
    case objectMLModelLaptop
    case objectMLModelMouse
    case objectMLModelRemote
    case objectMLModelKeyboard
    case objectMLModelCellPhone
    case objectMLModelMicrowave
    case objectMLModelOven
    case objectMLModelToaster
    case objectMLModelSink
    case objectMLModelRefrigerator
    case objectMLModelBook
    case objectMLModelClock
    case objectMLModelVase
    case objectMLModelScissors
    case objectMLModelTeddyBear
    case objectMLModelHairDrier
    case objectMLModelToothbrush
    
    case roadLightMLModelRed
    case roadLightMLModelGreen
}
